content:
  - name: pages
    label: Pages
    type: collection
    path: content
    format: md
    # This tells the CMS to use the filename for the list view
    identifier: name 
    fields:
      - name: title
        label: Page Title
        type: string
      - name: body
        label: Page Content
        type: rich-text
        isBody: true