content:
  - name: pages
    label: Pages
    type: collection
    path: content
    format: md
    # This forces the list to show "home", "about", etc.
    identifier: name
    fields:
      - name: title
        label: Page Title
        type: string
      - name: body
        label: Page Content
        type: rich-text
        isBody: true