content:
  - name: pages
    label: Pages
    type: collection
    path: content
    format: md
    identifier: title
    fields:
      - name: title
        label: title
        type: string
      - name: body
        label: content
        type: rich-text
        isBody: true
