content:
  - name: pages
    label: Pages
    type: collection
    path: content
    format: md
    fields:
      - name: title
        label: Page Title (For CMS only)
        type: string
      - name: body
        label: Page Content
        type: rich-text
        isBody: true
