content:
  - name: pages
    label: Pages
    type: collection
    path: content
    format: md
    fields:
      - name: title
        label: Title
        type: string
      - name: body
        label: Body
        type: rich-text