content:
  - name: pages
    label: Pages
    type: collection
    path: content       # folder containing markdown pages
    format: md          # markdown format
    identifier: title   # use front-matter 'title' as the label in CMS list
    fields:
      - name: title
        label: Page Title
        type: string
      - name: body
        label: Page Content
        type: rich-text
        isBody: true
