content:
  - name: pages
    label: Pages
    type: collection
    path: content
    format: md
    # This line tells the CMS to show the filename in the list
    identifier: title 
    fields:
      - name: title
        label: Title
        type: string
      - name: body
        label: Body
        type: rich-text