backend:
  name: github
  repo: wreckd-runner/wreckd
  branch: main   # must match your GitHub Pages branch


content:
  - name: pages
    label: Pages
    type: collection
    path: content
    format: md
    identifier: title
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: body
        label: Page Content
        type: rich-text
        isBody: true
